plugins {
    id 'java'
    id 'java-library'
    id("io.freefair.lombok") version "9.0.0-rc2"
    id("com.gradleup.shadow") version '9.1.0'
}


dependencies {
    api 'com.github.luben:zstd-jni:1.5.7-4'
    testCompileOnly 'io.netty:netty-all:4.2.6.Final'
    api "io.ib67.kiwi:lang:1.2.3-SNAPSHOT"
    implementation 'io.netty:netty-all:4.2.6.Final'
    implementation 'it.unimi.dsi:fastutil:8.5.15'
    implementation 'org.lz4:lz4-java:1.8.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

configurations {
    testRuntimeOnly {
        extendsFrom compileOnly
    }
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(Map.of("Main-Class", "io.ib67.sfcraft.bundler.Main"))
    }
}