plugins {
    id 'java'
    id 'java-library'
    id("io.freefair.lombok") version "9.0.0-rc2"
    id("com.gradleup.shadow") version '9.1.0'
}


dependencies {
    api 'com.github.luben:zstd-jni:1.5.7-4'
    compileOnly 'io.netty:netty-all:4.2.6.Final'
    api "io.ib67.kiwi:lang:1.2.3-SNAPSHOT"
    api 'io.netty:netty-all:4.2.6.Final'
}


jar {
    manifest {
        attributes(Map.of("Main-Class", "io.ib67.sfcraft.bundler.Main"))
    }
}